name: gbale
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
    
    # used for adaptiveness and responsiveness
  flutter_screenutil: ^5.6.0

  # Provider state management library extension with classes to boost mvvm architecture
  stacked: ^3.0.1
  stacked_hooks: ^0.2.2
  stacked_services: ^0.9.8
  

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.2.0
  stacked_generator: ^0.8.1
  


flutter:

 
  uses-material-design: true
  
  assets:
    - assets/fonts/
  #   - images/a_dot_ham.jpeg
 
  fonts:
    - family: LexendMega 
      fonts:
        - asset: fonts/LexendMega-Regular.ttf
        - asset: fonts/Black-Italic.ttf
        - asset: fonts/Bold-Italic.ttf
        - asset: fonts/ExtraBold-Italic.ttf
        - asset: fonts/ExtraLight-Italic.ttf
        - asset: fonts/Light-Italic.ttf
        - asset: fonts/Medium-Italic.ttf
        - asset: fonts/SemiBold-Italic.ttf
        - asset: fonts/Thin-Italic.ttf
        
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
